workflow:
  id: product-documentation
  name: 产品文档编写协作流程
  description: >-
    PO姜尚和UX专家嫦娥协作完成业务价值层文档编写的标准工作流。
    从项目简介到用户故事的完整文档链，确保业务需求准确传递到技术设计层。
  type: business-value
  team: business-value-layer
  project_types:
    - greenfield-project
    - feature-enhancement
    - product-planning
    - business-requirement

  sequence:
    - step: requirement_gathering
      agent: po
      action: 需求收集和分析
      creates: project-brief.md
      uses: project-brief-tmpl
      notes: "姜尚(姜子牙)负责收集业务需求，创建项目简介，明确产品目标和用户群体。"

    - step: user_research
      agent: ux-expert
      action: 用户研究和体验设计
      collaborates_with: po
      creates: user-research-insights.md
      uses: user-research-insights-tmpl
      notes: "嫦娥进行用户研究，提供用户画像、用户旅程和体验洞察，与姜尚协作完善用户理解。"

    - step: prd_creation
      agent: po
      action: 创建产品需求文档
      creates: prd.md
      uses: prd-tmpl
      requires: 
        - project-brief.md
        - user-research-insights.md
      collaborates_with: ux-expert
      notes: "姜尚主导创建PRD，嫦娥提供用户体验相关需求输入。SAVE OUTPUT: 将最终prd.md保存到项目的docs/文件夹。"

    - step: ux_specification
      agent: ux-expert
      action: 创建用户体验规格说明
      creates: ux-specification.md
      uses: ux-specification-tmpl
      requires: prd.md
      collaborates_with: po
      notes: "嫦娥基于PRD创建详细的用户体验规格，姜尚审核确保符合业务目标。"

    - step: epic_planning
      agent: po
      action: 史诗规划和分解
      creates: epic-*.md
      uses: epic-tmpl
      requires: 
        - prd.md
        - ux-specification.md
      notes: "姜尚将业务需求分解为史诗，明确MVP范围和业务价值。SAVE OUTPUT: 将史诗文档保存到docs/epics/文件夹。"

    - step: story_creation
      agent: po
      action: 用户故事创建
      creates: story-*.md
      uses: story-tmpl
      requires: epic-*.md
      collaborates_with: ux-expert
      notes: "姜尚创建详细用户故事，嫦娥提供用户体验验收标准输入。SAVE OUTPUT: 将故事文档保存到docs/stories/文件夹。"

    - step: business_validation
      agent: po
      action: 业务价值验证
      validates: all_business_artifacts
      uses: po-master-checklist
      notes: "姜尚验证所有业务文档的完整性、一致性和业务价值对齐。"

    - step: ux_validation
      agent: ux-expert
      action: 用户体验验证
      validates: user_experience_aspects
      notes: "嫦娥验证所有文档中的用户体验要求是否可实现且用户友好。"

    - step: collaborative_review
      agents: [po, ux-expert]
      action: 协作审查和完善
      condition: validation_issues_found
      notes: "如果发现问题，姜尚和嫦娥协作修正相关文档并重新验证。"

    - workflow_end:
      action: handoff_to_technical_layer
      notes: |
        业务价值层文档编写完成！现在移交给技术设计层：
        
        1. 确保文档已保存到项目中：
           - docs/project-brief.md (项目简介)
           - docs/prd.md (产品需求文档)
           - docs/ux-specification.md (用户体验规格)
           - docs/epics/ (史诗文档)
           - docs/stories/ (用户故事)
        
        2. 移交给架构师：
           - 提供完整的业务需求文档包
           - 明确技术约束和业务要求
           - 提供用户体验设计指导
        
        3. 后续开发准备：
           - 文档分片(shard)准备
           - 开发任务分解准备
           - 验收标准明确化
        
        参考: 技术设计层工作流程

  collaboration_patterns:
    po_ux_collaboration:
      frequency: 每个文档创建阶段都协作
      communication: 实时协作和异步审查相结合
      decision_making: PO姜尚为业务决策最终责任人，UX嫦娥为体验决策专家
      conflict_resolution: 优先用户价值，平衡业务目标和用户体验

  flow_diagram: |
    ```mermaid
    graph TD
        A[开始: 产品文档编写] --> B[姜尚: 需求收集 → project-brief.md]
        B --> C[嫦娥: 用户研究 → user-research-insights.md]
        C --> D[姜尚+嫦娥: 协作创建 prd.md]
        D --> E[嫦娥: UX规格 → ux-specification.md]
        E --> F[姜尚: 史诗规划 → epic-*.md]
        F --> G[姜尚+嫦娥: 用户故事 → story-*.md]
        G --> H[姜尚: 业务验证]
        H --> I[嫦娥: UX验证]
        I --> J{发现问题?}
        J -->|是| K[协作修正文档]
        J -->|否| L[移交技术设计层]
        K --> H

        style L fill:#90EE90
        style D fill:#FFE4B5
        style G fill:#FFE4B5
        style H fill:#E6E6FA
        style I fill:#E6E6FA
    ```

  decision_guidance:
    when_to_use:
      - 新产品或功能开发
      - 需要完整业务需求文档
      - 用户体验是关键成功因素
      - 跨团队协作项目
      - MVP定义和规划

  handoff_prompts:
    po_start: "开始需求收集，姜尚请创建项目简介，明确产品目标和目标用户。"
    ux_research: "项目简介完成，嫦娥请进行用户研究，提供用户洞察和体验建议。"
    collaborative_prd: "姜尚主导创建PRD，嫦娥协作提供用户体验需求输入。"
    ux_specification: "PRD完成，嫦娥请创建详细的用户体验规格说明。"
    epic_planning: "姜尚请基于PRD和UX规格进行史诗规划，明确MVP范围。"
    story_creation: "姜尚创建用户故事，嫦娥提供UX验收标准。"
    validation_phase: "姜尚进行业务验证，嫦娥进行UX验证。"
    collaboration_needed: "发现问题需要协作解决: [具体问题描述]"
    technical_handoff: "业务价值层文档完成，移交给技术设计层(鲁班+文殊菩萨)进行系统设计。"

  quality_gates:
    business_completeness:
      - 项目目标明确
      - 用户群体清晰
      - 业务价值可衡量
      - MVP范围合理
    
    user_experience_quality:
      - 用户研究充分
      - 用户旅程清晰
      - 体验目标明确
      - 可用性标准具体
    
    documentation_standards:
      - 所有模版字段完整
      - 业务技术边界清晰
      - 验收标准明确
      - 依赖关系识别

  metrics:
    efficiency:
      - 文档创建时间
      - 协作轮次
      - 修正次数
    
    quality:
      - 验收标准覆盖率
      - 用户价值清晰度
      - 技术移交顺畅度 