workflow:
  id: product-documentation
  name: 产品文档编写协作流程
  description: >-
    PO姜尚和UX专家嫦娥协作完成业务价值层文档编写的标准工作流。
    从项目简介到用户故事的完整文档链，确保业务需求准确传递到技术设计层。
  version: "0.0.1"
  created_date: "2025-01-08"
  type: business-value
  team: business-value-layer
  project_types:
    - greenfield-project
    - feature-enhancement
    - product-planning
    - business-requirement

  # 前置条件
  prerequisites:
    documents: []
    conditions:
      - "项目启动批准"
      - "初步业务目标确定"
    quality_gates: []

  sequence:
    - step: deep_research_phase
      name: "深度产品调研阶段"
      agent: po
      action: 启动深度产品调研流程

      inputs:
        required:
          - "项目基本概念"
          - "初步业务目标"
        optional:
          - "现有市场信息"
          - "用户反馈数据"

      outputs:
        creates:
          - "docs/deep-research-results/"

      uses:
        workflows:
          - "deep-product-research"

      quality_criteria:
        - "多维思维原则应用完整"
        - "用户洞察收集全面深入"
        - "创新机会识别充分"
        - "需求分析系统科学"

      completion_criteria:
        - "深度调研工作流完成"
        - "所有调研文档生成"
        - "批判性审查通过"

      validation:
        method: "multidimensional_review"
        validator: "po"
        criteria: "调研深度和多维思维应用质量"

      estimated_duration: "5-7工作日"
      notes: "产品负责人运用RIPER-5多维思维协议进行深度产品调研，系统收集用户想法并完善需求。"

    - step: requirement_gathering
      name: "需求收集和项目简介创建"
      agent: po
      action: 基于深度调研结果进行需求收集和分析

      inputs:
        required:
          - "docs/deep-research-results/"
          - "业务目标描述"
          - "目标用户群体信息"
        optional:
          - "竞品分析资料"
          - "市场调研数据"

      outputs:
        creates:
          - "docs/project-brief.md"

      uses:
        templates:
          - "project-brief-tmpl"

      quality_criteria:
        - "基于深度调研洞察"
        - "业务目标明确且可衡量"
        - "目标用户群体清晰定义"
        - "成功指标具体可量化"
        - "创新机会已识别"

      completion_criteria:
        - "项目简介文档完整"
        - "利益相关者确认业务目标"
        - "深度调研洞察已整合"

      validation:
        method: "stakeholder_review"
        validator: "po"
        criteria: "业务目标清晰度和调研洞察整合质量"

      estimated_duration: "1-2工作日"
      notes: "产品负责人基于深度调研成果收集业务需求，创建项目简介，确保洞察充分整合。"

    - step: user_research
      name: "用户研究和体验洞察"
      agent: ux-expert
      action: 用户研究和体验设计

      inputs:
        required:
          - "docs/project-brief.md"
        optional:
          - "现有用户数据"
          - "用户反馈记录"

      outputs:
        creates:
          - "docs/user-research-insights.md"

      uses:
        templates:
          - "user-research-insights-tmpl"

      collaborates_with:
        - agent: "po"
          interaction_type: "sync"
          frequency: "daily"

      quality_criteria:
        - "用户画像基于真实数据"
        - "用户旅程完整清晰"
        - "痛点和需求明确识别"

      completion_criteria:
        - "用户研究文档完整"
        - "产品负责人确认用户洞察"

      validation:
        method: "peer_review"
        validator: "po"
        criteria: "用户洞察的准确性和可操作性"

      estimated_duration: "2-3工作日"
      notes: "UX专家进行用户研究，提供用户画像、用户旅程和体验洞察，与产品负责人协作完善用户理解。"

    - step: prd_creation
      name: "产品需求文档创建"
      agent: po
      action: 创建产品需求文档

      inputs:
        required:
          - "docs/project-brief.md"
          - "docs/user-research-insights.md"
          - "docs/deep-research-results/"
          - "完整的项目信息收集清单"
        optional:
          - "竞品分析资料"
          - "技术约束文档"

      outputs:
        creates:
          - "docs/prd.md"

      uses:
        templates:
          - "prd-tmpl"
        checklists:
          - "project-info-collection-tmpl"

      quality_criteria:
        - "基于深度调研洞察创建"
        - "多维思维原则应用体现"
        - "用户想法充分整合"
        - "创新机会明确识别"
        - "文档不包含任何AI角色信息"
        - "使用当前实际日期"
        - "团队信息基于真实数据或留空"
        - "功能需求完整详细"
        - "验收标准具体可测"

      completion_criteria:
        - "PRD文档完整且符合模板要求"
        - "所有变量已正确填写"
        - "文档已保存到docs/目录"

      validation:
        method: "document_review"
        validator: "po"
        criteria: "文档完整性和信息准确性"

      estimated_duration: "1-2工作日"
      notes: "产品负责人基于收集的项目信息创建PRD，确保文档不包含AI角色信息且使用真实数据。SAVE OUTPUT: 将最终prd.md保存到项目的docs/文件夹。"

    - step: ux_specification
      agent: ux-expert
      action: 创建用户体验规格说明
      creates: ux-specification.md
      uses: ux-specification-tmpl
      requires: prd.md
      collaborates_with: po
      notes: "UX专家基于PRD创建详细的用户体验规格，产品负责人审核确保符合业务目标。"

    - step: epic_planning
      agent: po
      action: 史诗规划和分解
      creates: epic-*.md
      uses: epic-tmpl
      requires:
        - prd.md
        - ux-specification.md
      notes: "产品负责人将业务需求分解为史诗，明确MVP范围和业务价值。SAVE OUTPUT: 将史诗文档保存到docs/epics/文件夹。"

    - step: story_creation
      agent: po
      action: 用户故事创建
      creates: story-*.md
      uses: story-tmpl
      requires: epic-*.md
      collaborates_with: ux-expert
      notes: "产品负责人创建详细用户故事，UX专家提供用户体验验收标准输入。SAVE OUTPUT: 将故事文档保存到docs/stories/文件夹。"

    - step: business_validation
      agent: po
      action: 业务价值验证
      validates: all_business_artifacts
      uses: po-master-checklist
      notes: "产品负责人验证所有业务文档的完整性、一致性和业务价值对齐。"

    - step: ux_validation
      agent: ux-expert
      action: 用户体验验证
      validates: user_experience_aspects
      notes: "UX专家验证所有文档中的用户体验要求是否可实现且用户友好。"

    - step: collaborative_review
      agents: [po, ux-expert]
      action: 协作审查和完善
      condition: validation_issues_found
      notes: "如果发现问题，产品负责人和UX专家协作修正相关文档并重新验证。"

    - workflow_end:
      action: handoff_to_technical_layer
      notes: |
        业务价值层文档编写完成！现在移交给技术设计层：
        
        1. 确保文档已保存到项目中：
           - docs/project-brief.md (项目简介)
           - docs/prd.md (产品需求文档)
           - docs/ux-specification.md (用户体验规格)
           - docs/epics/ (史诗文档)
           - docs/stories/ (用户故事)
        
        2. 移交给架构师：
           - 提供完整的业务需求文档包
           - 明确技术约束和业务要求
           - 提供用户体验设计指导
        
        3. 后续开发准备：
           - 文档分片(shard)准备
           - 开发任务分解准备
           - 验收标准明确化
        
        参考: 技术设计层工作流程

# === 交接机制 ===
  handoff:
    to:
      - workflow: "technical-design"
        team: "technical-design-layer"
        trigger_condition: "所有业务价值层文档完成并验证通过"
        handoff_ceremony:
          name: "PRD评审会"
          participants: ["产品负责人", "UX专家", "架构师", "QA负责人"]
          duration: "90分钟"
          agenda:
            - "PRD文档完整性检查"
            - "用户故事验收标准确认"
            - "UX设计规格说明"
            - "技术约束和非功能需求澄清"
            - "实现优先级和时间估算"
          deliverables:
            - "完整的业务需求文档包"
            - "技术设计任务清单"
            - "质量标准确认书"

    from: []

  # === 质量门禁 ===
  quality_gates:
    entry_criteria:
      - name: "项目启动就绪"
        description: "项目获得批准，初步业务目标确定"
        validation_method: "stakeholder_approval"

    milestone_gates:
      - milestone: "需求收集完成"
        criteria:
          - "项目简介文档完整"
          - "业务目标明确可衡量"
          - "目标用户群体清晰"
        validation_method: "document_review"

      - milestone: "用户研究完成"
        criteria:
          - "用户画像基于真实数据"
          - "用户旅程完整清晰"
          - "用户需求和痛点明确"
        validation_method: "peer_review"

      - milestone: "PRD创建完成"
        criteria:
          - "功能需求完整详细"
          - "非功能需求明确"
          - "验收标准具体可测"
        validation_method: "stakeholder_review"

    exit_criteria:
      - name: "业务价值层文档完整"
        description: "所有必需文档创建完成并通过验证"
        validation_method: "comprehensive_review"

      - name: "技术移交就绪"
        description: "技术设计层能够基于文档开始工作"
        validation_method: "handoff_ceremony"

  collaboration_patterns:
    po_ux_daily_sync:
      participants: ["产品负责人", "UX专家"]
      frequency: "daily"
      duration: "15分钟"
      format: "sync"
      purpose: "进度同步和问题解决"
      agenda:
        - "昨日完成工作回顾"
        - "今日工作计划"
        - "阻塞问题讨论"
      outcomes:
        - "工作进度对齐"
        - "问题解决方案"

    collaborative_document_creation:
      participants: ["产品负责人", "UX专家"]
      frequency: "per_milestone"
      duration: "60-120分钟"
      format: "sync"
      purpose: "协作创建关键文档"
      agenda:
        - "需求澄清和确认"
        - "用户体验要求讨论"
        - "文档内容协作编写"
      outcomes:
        - "高质量的协作文档"
        - "业务和用户价值对齐"

  flow_diagram: |
    ```mermaid
    graph TD
        A[开始: 产品文档编写] --> B[产品负责人: 需求收集 → project-brief.md]
        B --> C[UX专家: 用户研究 → user-research-insights.md]
        C --> D[产品负责人+UX专家: 协作创建 prd.md]
        D --> E[UX专家: UX规格 → ux-specification.md]
        E --> F[产品负责人: 史诗规划 → epic-*.md]
        F --> G[产品负责人+UX专家: 用户故事 → story-*.md]
        G --> H[产品负责人: 业务验证]
        H --> I[UX专家: UX验证]
        I --> J{发现问题?}
        J -->|是| K[协作修正文档]
        J -->|否| L[移交技术设计层]
        K --> H

        style L fill:#90EE90
        style D fill:#FFE4B5
        style G fill:#FFE4B5
        style H fill:#E6E6FA
        style I fill:#E6E6FA
    ```

  decision_guidance:
    when_to_use:
      - 新产品或功能开发
      - 需要完整业务需求文档
      - 用户体验是关键成功因素
      - 跨团队协作项目
      - MVP定义和规划

  handoff_prompts:
    deep_research_start: "[RESEARCH模式] 开始深度产品调研，运用多维思维进行全面需求分析。"
    po_start: "深度调研完成，开始基于调研洞察进行需求收集和项目简介创建。"
    ux_research: "项目简介完成，UX专家请进行用户研究，提供用户洞察和体验建议。"
    collaborative_prd: "产品负责人主导创建PRD，整合深度调研成果，UX专家协作提供用户体验需求输入。"
    ux_specification: "PRD完成，UX专家请创建详细的用户体验规格说明。"
    epic_planning: "产品负责人请基于PRD和UX规格进行史诗规划，明确MVP范围。"
    story_creation: "产品负责人创建用户故事，UX专家提供UX验收标准。"
    validation_phase: "产品负责人进行业务验证，UX专家进行UX验证。"
    collaboration_needed: "发现问题需要协作解决: [具体问题描述]"
    technical_handoff: "业务价值层文档完成，移交给技术设计层(架构师+QA负责人)进行系统设计。"

# === 度量指标 ===
  metrics:
    efficiency:
      - name: "文档创建时间"
        target: "< 5工作日"
        measurement: "从开始到完成的实际时间"
      - name: "协作轮次"
        target: "< 3轮修正"
        measurement: "文档修正和确认的轮次"

    quality:
      - name: "验收标准覆盖率"
        target: "> 95%"
        measurement: "有明确验收标准的用户故事比例"
      - name: "用户价值清晰度"
        target: "> 4.5/5.0"
        measurement: "技术团队对用户价值理解的评分"
      - name: "技术移交顺畅度"
        target: "> 90%"
        measurement: "技术团队能够直接开始工作的比例"

# === 成功标准 ===
  success_criteria:
    functional:
      - "所有必需文档创建完成"
      - "用户故事具备明确验收标准"
      - "业务价值和用户价值清晰定义"
    quality:
      - "文档内容准确完整"
      - "业务和技术边界清晰"
      - "用户体验要求具体可实现"
    business:
      - "业务目标与用户需求对齐"
      - "MVP范围合理可行"
      - "投资回报预期明确"